program: experiment.py

method: grid
metric:
  goal: maximize
  name: Episode_Return

parameters:
  critic_optimiser:
    values: [adam, adagrad, sgd, accelerated_sgd, accelerated_sgd_adagrad]
  experiment.mlmc_correction_actor:
    values: [true, false]
  experiment.mlmc_correction_critic:
    values: [true, false]
  seed:
    values: [1, 11, 111]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args_no_hyphens}