seed: 0
actor_optimiser: adam
critic_optimiser: adam

momentum:
  decay_theta: 0.87
  decay_eta: 3.2
  decay_beta: 0.15
  decay_p: 0.48

learning_rate: 1.E-3

experiment:
  env_id: CartPole-v1
  n_training_episodes: 250000
  batchsize_bound: 5
  max_t: 500
  batchsize_limit: 32
  gamma: 0.99
  mlmc_correction_actor: false
  mlmc_correction_critic: false
  total_samples: null
  env_kwargs:
    map_filename: null
    map_name: null
    on_target: restart 
    size: 8  # size of the grid
    density: 0.0  # obstacle density
    max_episode_steps: 64  # horizon
    obs_radius: 1  # defines field of view

wandb:
  project: MLMCOptimiser 
  # name: actor_critic_montecarlo
  entity: alexunderch