seed: 0
optimiser: adam

momentum:
  decay_theta: 0.87
  decay_eta: 3.2
  decay_beta: 0.15
  decay_p: 0.48

learning_rate: 3.E-4
alpha: 3.E-4
anneal_lr: false

experiment:
  env_id: "navix:Navix-DoorKey-5x5-v0" # navix:Navix-Empty-8x8-v0 #CartPole-v1
  n_training_episodes: 100000
  batchsize_bound: 128
  max_t: 500
  batchsize_limit: 64
  gae_lambda: 0.999
  vf_coeff: 0.5
  clip_eps: 0.2
  ent_coeff: 0.01
  av_vf_coeff: 0.01
  projection: "softmax"
  mlmc_correction: false
  total_samples: null
  env_kwargs:
    on_target: restart
    size: 8  # size of the grid
    density: 0.0  # obstacle density
    max_episode_steps: 128  # horizon
    obs_radius: 1  # defines field of view

wandb:
  project: MLMCOptimiser 
  # name: actor_critic_ppo
  entity: alexunderch