seed: 0
optimiser: adam
critic_optimiser: adam


momentum:
  decay_theta: 0.87
  decay_eta: 3.2
  decay_beta: 0.15
  decay_p: 0.48

learning_rate: 3.E-4
alpha: 3.E-4
anneal_lr: false

experiment:
  env_id: navix:Navix-Empty-5x5-v0 #jaxnav #navix:Navix-Empty-5x5-v0 #navix:Navix-Empty-8x8-v0  #"navix:Navix-DoorKey-5x5-v0" # navix:Navix-Empty-8x8-v0 #CartPole-v1
  num_envs: 1
  n_training_episodes: 1000000
  batchsize_bound: 128
  max_t: 500
  batchsize_limit: 32
  gae_lambda: 0.95
  vf_coeff: 1.0
  clip_eps: 0.2
  ent_coeff: 0.01
  av_vf_coeff: 0.1
  mlmc_correction: false
  total_samples: 1000000


wandb:
  project: MLMCOptimiser 
  # name: actor_critic_ppo
  entity: alexunderch