program: experiment.py

method: grid
metric:
  goal: maximize
  name: Episode_Return

parameters:
  experiment.num_envs:
    values: [2]
  experiment.projection: 
    values: [softmax] #["softmax", "simplex"]
  experiment.gae_lambda: 
    values: [0.95] 
  experiment.batchsize_bound: 
    values: [128]
  experiment.batchsize_limit: 
    values: [32]
  experiment.env_id:
    values: [navix:Navix-DoorKey-5x5-v0]
  optimiser:
    values: [adam]
  experiment.mlmc_correction:
    values: [true, false]
  seed:
    values: [0, 1, 10, 11, 100]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args_no_hyphens}