program: experiment.py


method: grid
metric:
  goal: maximize
  name: Episode_Return

parameters:
  experiment.projection: 
    values: [softmax] #["softmax", "simplex"]
  experiment.total_samples: 
    values: [1.E+6]
  experiment.batchsize_bound: 
    values: [128]
  experiment.env_id:
    values: [navix:Navix-Empty-8x8-v0] #[pogema, CartPole-v1, Acrobot-v1]
  optimiser:
    values: [adam]
  experiment.mlmc_correction:
    values: [true, false]
  seed:
    values: [0, 1, 11]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args_no_hyphens}