program: experiment.py

method: grid
metric:
  goal: maximize
  name: Episode_Return

parameters:
  experiment.num_envs:
    values: [10]
  experiment.gae_lambda: 
    values: [0.95] 
  experiment.batchsize_bound: 
    values: [64]
  experiment.batchsize_limit: 
    values: [16]
  experiment.env_id:
    values: [jaxnav, navix:Navix-Empty-5x5-v0, navix:Navix-DoorKey-5x5-v0]
  optimiser:
    values: [adam, adamw, mamd]
  experiment.mlmc_correction:
    values: [true, false]
  seed:
    values: [0, 1, 10, 11, 100]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args_no_hyphens}