program: experiment.py

method: grid
metric:
  goal: maximize
  name: Episode_Return

parameters:
  experiment.num_envs:
    values: [16]
  experiment.gae_lambda: 
    values: [0.95] 
  experiment.batchsize_bound: 
    values: [2, 16]
  experiment.batchsize_limit: 
    values: [2, 32]
  experiment.projection: 
    values: ["simplex", "l2"]
  experiment.env_id:
    values: [navix:Navix-Empty-5x5-v0]
  optimiser:
    values: [adam]
  experiment.mlmc_correction:
    values: [true, false]
  seed:
    values: [0, 1, 10]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args_no_hyphens}