program: experiment.py

method: grid
metric:
  goal: maximize
  name: Episode_Return

parameters:
  experiment.projection: 
    values: ["simplex", "l2"] #["softmax", "simplex"]
  experiment.num_envs:
    values: [8]
  experiment.gae_lambda: 
    values: [0.95] 
  experiment.batchsize_bound: 
    values: [2, 16]
  experiment.batchsize_limit: 
    values: [2, 32]
  experiment.total_samples: 
    values: [100000]
  experiment.env_id:
    values: [CartPole-v1, Acrobot-v1] 
  optimiser:
    values: [adam, mamd]
  experiment.mlmc_correction:
    values: [true, false]
  seed:
    values: [0, 1, 10]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args_no_hyphens}