program: experiment.py

method: grid
metric:
  goal: maximize
  name: Episode_Return

parameters:
  type: 
    values: ["mc", "td0"]
  experiment.env_id:
    values: [CartPole-v1, Acrobot-v1]
  critic_optimiser:
    values: [adam, adagrad, sgd, accelerated_sgd, accelerated_sgd_adagrad]
  actor_optimiser:
    values: [adam, adagrad, sgd]
  experiment.mlmc_correction_actor:
    values: [true, false]
  experiment.mlmc_correction_critic:
    values: [true, false]
  seed:
    values: [1, 11, 111]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args_no_hyphens}