seed: 0
optimiser: adam
learning_rate: 1.E-2

experiment:
  env_id: CartPole-v1
  n_training_episodes: 5000
  batchsize_bound: 250
  batchsize_limit: 16
  gamma: 0.99
  mlmc_correction: false

wandb:
  project: MLMCOptimiser 
  entity: alexunderch