seed: 0
optimiser: sgd
critic_optimiser: sgd

learning_rate: 3.E-4
alpha: 3.E-4
anneal_lr: false

experiment:
  env_id: navix:Navix-Empty-6x6-v0 #jaxnav #navix:Navix-Empty-5x5-v0 #navix:Navix-Empty-8x8-v0  #"navix:Navix-DoorKey-5x5-v0" # navix:Navix-Empty-8x8-v0 #CartPole-v1
  num_envs: 10
  n_training_episodes: 1000000
  batchsize_bound: 2
  gd_epochs: 2
  batchsize_limit: 2
  gae_lambda: 0.95
  vf_coeff: 0.5
  clip_eps: 0.2
  ent_coeff: 0.01
  av_vf_coeff: 0.01
  mlmc_correction: true
  total_samples: 100000


wandb:
  project: MLMCOptimiser 
  # name: actor_critic_ppo
  entity: alexunderch