seed: 0
actor_optimiser: adam
critic_optimiser: adam

momentum:
  decay_theta: 0.87
  decay_eta: 3.2
  decay_beta: 0.15
  decay_p: 0.48

learning_rate: 3.E-3

experiment:
  env_id: pogema
  n_training_episodes: 20000
  batchsize_bound: 2
  max_t: 500
  batchsize_limit: 8
  mlmc_correction_actor: false
  mlmc_correction_critic: false
  env_kwargs:
    on_target: restart
    size: 8  # size of the grid
    density: 0.0  # obstacle density
    max_episode_steps: 64  # horizon
    obs_radius: 1  # defines field of view
wandb:
  project: MLMCOptimiser 
  # name: actor_critic_montecarlo
  entity: alexunderch