seed: 0
optimiser: adam
learning_rate: 1.E-3

experiment:
  env_id: CartPole-v1
  n_training_episodes: 1000
  batchsize_bound: 500
  max_t: 500
  batchsize_limit: 700
  gamma: 0.99
  mlmc_correction: false

wandb:
  project: MLMCOptimiser 
  entity: alexunderch