seed: 0
optimiser: adam

momentum:
  decay_theta: 0.87
  decay_eta: 3.2
  decay_beta: 0.15
  decay_p: 0.48

learning_rate: 2.5E-4
anneal_lr: false

experiment:
  env_id: CartPole-v1
  n_training_episodes: 2000
  batchsize_bound: 200
  max_t: 500
  batchsize_limit: 61
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coeff: 0.5
  ent_coeff: 1.E-2
  mlmc_correction: false

wandb:
  project: MLMCOptimiser 
  # name: actor_critic_ppo
  entity: alexunderch