program: experiment_ppo.py


method: grid
metric:
  goal: maximize
  name: Episode_Return

parameters:
  experiment.env_id:
    values: [CartPole-v1, Acrobot-v1]
  optimiser:
    values: [adam, adagrad, sgd, accelerated_sgd, accelerated_sgd_adagrad]
  experiment.mlmc_correction:
    values: [true, false]
  seed:
    values: [1, 11, 111]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args_no_hyphens}